projectSteamIndex/website/auth.py
from datetime import datetime

import pandas as pd
from flask import Blueprint, render_template, jsonify, send_from_directory, request, url_for, redirect
import os
import website.downloadYT as downloadYT
import website.sentimentScore as sentimentScore
import website.showReports as showReports
from website.DatabaseConnector import DatabaseConnector
from urllib.parse import unquote
from datetime import datetime, timedelta


auth = Blueprint('auth', __name__)


@auth.route('/videos', methods=['GET','POST'])
def videos():
    return render_template("videos.html")


@auth.route('/sentiment', methods=['GET','POST'])
def sentiment():
    return render_template("sentiment.html")


@auth.route('/reports', methods=['GET','POST'])
def reports():
    return render_template('reports.html')


@auth.route('/view-reports', methods=['GET','POST'])
def view_reports():
    return render_template('viewreports.html')


@auth.route('/projections')
def projections():
    return render_template('projections.html')


@auth.route('/admin-projections', methods=['GET', 'POST'])
def admin_projections():
    return render_template('admin_projections.html')


@auth.route('/download-yt', methods=['POST'])
def download_yt():
    try:
        downloadYT.main()
        return jsonify({"message": "Script executed successfully!"}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@auth.route('/generate-sentiment', methods=['POST'])
def generate_sentiment():
    try:
        sentimentScore.main()
        return jsonify({"message": "Script executed successfully!"}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@auth.route('/get-sentiments', methods=['GET'])
def get_sentiments():
    db = DatabaseConnector()

    start_date = request.args.get('start_date')
    end_date = request.args.get('end_date')

    # Construct the base SQL query
    # sentiment_query = '''
    #     SELECT name, position, team, sentiment, COUNT(name) as num_quotes
    #     FROM quotes
    # '''
    sentiment_quotes_query = '''
        SELECT name, position, team, sentiment
        FROM quotes
    '''
    # Initialize an empty list to hold the WHERE clauses
    where_clauses = ['sentiment IS NOT NULL']

    # Add the date range conditions if start_date and end_date are provided
    if start_date and end_date:
        where_clauses.append("date >= '{}' AND date <= '{}'".format(start_date, end_date))

    # If there are any WHERE clauses, add them to the query
    if where_clauses:
        sentiment_quotes_query += ' WHERE ' + ' AND '.join(where_clauses)
    sentiments_quotes_df = db.query_dataframe(sentiment_quotes_query)


    allPlayers_query = "SELECT name, position, team FROM allPlayers"
    allPlayers_df = db.query_dataframe(allPlayers_query)

    sentiment_reports_query = '''
        SELECT player_name as name, sentiment
        FROM reports
    '''
    # Initialize an empty list to hold the WHERE clauses
    where_clauses_reports = ['sentiment IS NOT NULL']

    # Add the date range conditions if start_date and end_date are provided
    if start_date and end_date:
        where_clauses_reports.append("report_date >= '{}' AND report_date <= '{}'".format(start_date, end_date))

    # If there are any WHERE clauses, add them to the query
    if where_clauses_reports:
        sentiment_reports_query += ' WHERE ' + ' AND '.join(where_clauses_reports)
    sentiments_reports_df = db.query_dataframe(sentiment_reports_query)

    df_combined_reports_players = pd.merge(sentiments_reports_df, allPlayers_df, on='name', how='left')

    df_combined_reports_quotes = pd.concat([df_combined_reports_players, sentiments_quotes_df], ignore_index=True)

    avg_sentiments = df_combined_reports_quotes.groupby(['name', 'position', 'team'])['sentiment'].mean().reset_index()

    # Query to fetch total number of quotes per player
    query_quotes = '''
    SELECT name, COUNT(name) as num_quotes
    FROM quotes
    '''
    if start_date and end_date:
        query_quotes += '''
            WHERE date >= '{}' AND date <= '{}'
        '''.format(start_date, end_date)
    query_quotes += '''
        GROUP BY name
    '''
    df_num_quotes = db.query_dataframe(query_quotes)

    # Query to fetch total number of reports per player
    query_reports = '''
    SELECT player_name as name, COUNT(player_name) as num_reports
    FROM reports
    '''
    if start_date and end_date:
        query_reports += '''
            WHERE report_date >= '{}' AND report_date <= '{}'
        '''.format(start_date, end_date)
    query_reports += '''
        GROUP BY name
    '''
    df_num_reports = db.query_dataframe(query_reports)

    df_merged = pd.merge(avg_sentiments, df_num_quotes, on='name', how='left')
    df_merged = pd.merge(df_merged, df_num_reports, on='name', how='left')
    df_merged['num_quotes'] = df_merged['num_quotes'].fillna(0).astype(int)
    df_merged['num_reports'] = df_merged['num_reports'].fillna(0).astype(int)
    df_sorted = df_merged.sort_values(by='sentiment', ascending=False)
    db.close()
    result = df_sorted.to_dict(orient='records')
    return jsonify(result)



BASE_VIDEO_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'videos'))


@auth.route('/list-videos', methods=['GET'])
def list_videos():
    videos_all = []
    for root, dirs, files in os.walk(BASE_VIDEO_PATH):
        for video_file in files:
            video_path = os.path.join(root, video_file)
            team_dir = os.path.relpath(root, BASE_VIDEO_PATH).split(os.sep)[0]  # Get the team directory name
            if os.path.isfile(video_path) and video_file != 'downloaded_videos.json':
                videos_all.append({
                    'team': team_dir,
                    'title': video_file,
                    'path': os.path.relpath(video_path, BASE_VIDEO_PATH).replace(os.sep, '/'),
                    'date': datetime.fromtimestamp(os.path.getmtime(video_path)).strftime('%Y-%m-%d %H:%M:%S')
                })
    return jsonify(videos_all)


@auth.route('/delete-video', methods=['POST'])
def delete_video():
    data = request.json
    not_found_videos = []

    for video_path in data['paths']:
        decoded_path = unquote(video_path)
        full_video_path = os.path.join(BASE_VIDEO_PATH, os.path.normpath(decoded_path))
        # print(f"Received path for deletion: {full_video_path}")  # Log the received path
        if os.path.exists(full_video_path):
            os.remove(full_video_path)
            print(f"Deleted: {full_video_path}")  # Log successful deletion
        else:
            print(f"File not found: {full_video_path}")  # Log file not found
            not_found_videos.append(video_path)

    if not_found_videos:
        return jsonify({'error': f'These videos were not found: {", ".join(not_found_videos)}'}), 404
    return jsonify({'message': 'Videos deleted successfully'}), 200


@auth.route('/videos/<path:filename>')
def get_video(filename):
    decoded_path = unquote(filename)
    full_path = os.path.join(BASE_VIDEO_PATH, os.path.normpath(decoded_path))
    if os.path.exists(full_path):
        return send_from_directory(BASE_VIDEO_PATH, decoded_path)
    else:
        return "Not Found", 404


@auth.route('/submit', methods=['POST'])
def submit_reports():
    if request.method == 'POST':
        player_names = request.form.getlist('playerName[]')
        report_dates = request.form.getlist('reportDate[]')
        sources = request.form.getlist('source[]')
        report_texts = request.form.getlist('reportText[]')
        questions = request.form.getlist('question[]')

        # Validate form data (example: check if fields are not empty)
        db = DatabaseConnector()
        add_report = ("INSERT INTO reports"
                      "(player_name, report_date, source, report_text, question)"
                      "VALUES (%s, %s, %s, %s, %s)")
        # Validate and insert each report
        for i in range(len(player_names)):
            player_name = player_names[i]
            report_date = report_dates[i]
            source = sources[i]
            report_text = report_texts[i]
            question = questions[i] if i < len(questions) else None  # Optional question

            if player_name and report_date and source and report_text:
                reports_data = (player_name, report_date, source, report_text, question)
                db.insert(add_report, reports_data)
            else:
                return f"Error: Report {i+1} has missing fields."
        db.close()
        return redirect(url_for('auth.reports'))  # Redirect to index after all reports are inserted

    return "Error: Invalid request method."


@auth.route('/get_all_players')
def get_all_players():
    try:
        db = DatabaseConnector()
        query = "SELECT name FROM allPlayers ORDER BY name ASC"
        results = db.query(query)

        # Extract player names from the query results
        player_names = [row[0] for row in results]
        db.close()
        return jsonify(player_names)

    except Exception as e:
        return jsonify({'error': str(e)}), 500


@auth.route('/all-reports', methods=['GET'])
def all_reports():
    try:
        player_name = request.args.get('player', None)
        start_date = request.args.get('start_date')
        end_date = request.args.get('end_date')
        all_reports_df = showReports.get_reports(player_name, start_date, end_date)
        return jsonify(all_reports_df)
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@auth.route('/delete-reports', methods=['POST'])
def delete_reports():
    try:
        data = request.json
        print(data)
        report_ids = data.get('reportIds', [])

        if not report_ids:
            return jsonify({'error': 'No report IDs provided'}), 400

        db = DatabaseConnector()
        delete_query = "DELETE FROM reports WHERE id IN ({})".format(','.join(['%s'] * len(report_ids)))

projectSteamIndex/website/templates/admin_projections.html
{% extends "base.html" %} <!-- saying this template is the exact same as base.html and I can override any blocks that were defined within base.html -->
{% block title %}Admin{% endblock %} <!-- overriding the block within base.html -->
{% block stylesheet %}<link href="static/admin_projections.css" rel="stylesheet"> {% endblock %} <!-- overriding the block stylesheet within base.html -->
{% block content %}
<h4 class="mt-5">Admin Projections</h4>
<div id="loadingSpinner" class="loading-spinner" style="display: none;">
    <div class="spinner-border text-primary" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>

<div class="filter-bar mt-2">
    <input type="text" id="searchInput" class="form-control" placeholder="Search by Player Name">
    <select id="teamFilter" class="form-control">
        <option value="Cardinals" selected>Arizona Cardinals</option>
        <option value="Falcons">Atlanta Falcons</option>
        <option value="Ravens">Baltimore Ravens</option>
        <option value="Bills">Buffalo Bills</option>
        <option value="Panthers">Carolina Panthers</option>
        <option value="Bears">Chicago Bears</option>
        <option value="Bengals">Cincinnati Bengals</option>
        <option value="Browns">Cleveland Browns</option>
        <option value="Cowboys">Dallas Cowboys</option>
        <option value="Broncos">Denver Broncos</option>
        <option value="Lions">Detroit Lions</option>
        <option value="Packers">Green Bay Packers</option>
        <option value="Texans">Houston Texans</option>
        <option value="Colts">Indianapolis Colts</option>
        <option value="Jaguars">Jacksonville Jaguars</option>
        <option value="Chiefs">Kansas City Chiefs</option>
        <option value="Raiders">Las Vegas Raiders</option>
        <option value="Chargers">Los Angeles Chargers</option>
        <option value="Rams">Los Angeles Rams</option>
        <option value="Dolphins">Miami Dolphins</option>
        <option value="Vikings">Minnesota Vikings</option>
        <option value="Patriots">New England Patriots</option>
        <option value="Saints">New Orleans Saints</option>
        <option value="Giants">NY Giants</option>
        <option value="Jets">NY Jets</option>
        <option value="Eagles">Philadelphia Eagles</option>
        <option value="Steelers">Pittsburgh Steelers</option>
        <option value="49ers">San Francisco 49ers</option>
        <option value="Seahawks">Seattle Seahawks</option>
        <option value="Buccaneers">Tampa Bay Buccaneers</option>
        <option value="Titans">Tennessee Titans</option>
        <option value="Commanders">Washington Commanders</option>
    </select>
    <select id="positionFilter" class="form-control">
        <option value="">Select Position</option>
        <option value="QB">QB</option>
        <option value="RB">RB</option>
        <option value="WR">WR</option>
        <option value="TE">TE</option>
    </select>
    <button id="deleteButton" class="btn btn-danger">Delete Selected</button>
    <button id="resetButton" class="btn btn-primary">Reset Filters</button>
    <button id="saveButton" class="btn btn-success">Save Changes</button>


</div>

<div class="table-responsive mt-3">
    <table class="table table-bordered table-striped" id="qbTable">
        <thead class="thead-dark">
        <tr>
            <th><input type="checkbox" id="selectAllQBs" name="selectAllQBs"></th>
            <th>#</th>
            <th>Name</th>
            <th>Pos.</th>
            <th>School</th>
            <th>Orig</th>
            <th>Exp</th>
            <th>Gms</th>
            <th>Att</th>
            <th>Cmp</th>
            <th>Pct</th>
            <th>Yds</th>
            <th>YPA</th>
            <th>TD</th>
            <th>TD%</th>
            <th>Int</th>
            <th>YPG</th>
            <th>Sack</th>
            <th>RAtt</th>
            <th>RYds</th>
            <th>RAvg</th>
            <th>RYPG</th>
            <th>RLg</th>
            <th>RTD</th>
            <th class="notes">Notes</th>
        </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
<div class="table-responsive mt-3">
    <table class="table table-bordered table-striped" id="skillPositionTable">
        <thead class="thead-dark">
        <tr>
            <th><input type="checkbox" id="selectAll" name="selectAll"></th>
            <th>#</th>
            <th>Name</th>
            <th>Pos.</th>
            <th>School</th>
            <th>Orig</th>
            <th>Exp</th>
            <th>Gms</th>
            <th>RAtt</th>
            <th>RYds</th>
            <th>RAvg</th>
            <th>RYPG</th>
            <th>RLg</th>
            <th>RTD</th>
            <th>Rec</th>
            <th>ReYds</th>
            <th>ReAvg</th>
            <th>ReYpg</th>
            <th>ReLg</th>
            <th>ReTD</th>
            <th>Tar</th>
            <th class="notes">Notes</th>
        </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
<script type="text/javascript" src="{{ url_for('static', filename='admin_projections.js') }}"></script>
{% endblock %}

projectSteamIndex/website/templates/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
    />  <!-- Importing bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link href="static/base.css" rel="stylesheet">
    {% block stylesheet %}{% endblock %}
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbar"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                <a class="nav-item nav-link" id="home" href="/">Quotes</a>
                <a class="nav-item nav-link" id="sentiment" href="/sentiment">Sentiment</a>
                <a class="nav-item nav-link" id="videos" href="/videos">Videos</a>
                <a class="nav-item nav-link" id="reports" href="/reports">Create Reports</a>
                <a class="nav-item nav-link" id="view_reports" href="/view-reports">View Reports</a>
                <a class="nav-item nav-link" id="projections" href="/projections">Projections</a>
                <a class="nav-item nav-link" id="admin_projections" href="/admin-projections">Admin</a>
            </div>
        </div>
    </nav>
    <!-- looping thru the error messages -->
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}



    <div class="container">
        {% block content %} {% endblock %}
    </div>


<!-- scripts for bootstrap -->
    <script
            src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"
    ></script>
    <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"
    ></script>
    <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"
    ></script>

    <!-- for loading in any javascript within the static folder -->
<!--    <script-->
<!--        type="text/javascript"-->
<!--        src="{{ url_for('static', filename='index.js') }}"-->
<!--    ></script> -->


</body>
</html>

projectSteamIndex/website/templates/home.html
{% extends "base.html" %} <!-- saying this template is the exact same as base.html and I can override any blocks that were defined within base.html -->
{% block title %}Home{% endblock %} <!-- overriding the block within base.html -->
{% block stylesheet %}<link href="static/quotes.css" rel="stylesheet"> {% endblock %} <!-- overriding the block stylesheet within base.html -->
{% block content %}
<h2 class="mt-5">Quotes</h2>
<button type="submit" class="btn btn-primary" onClick="generate_transcript()">Generate Transcripts</button>
<button id="deleteSelected" class="btn btn-danger" onClick="deleteSelectedQuotes()" disabled>Delete Selected</button>
<p id="result2"></p>
<div class="filter-bar mt-2">
    <input type="text" id="searchInput" class="form-control" placeholder="Search by player name">
    <select id="teamFilter" class="form-control">
        <option value="">Select Team</option>
        <option value="Arizona Cardinals">Arizona Cardinals</option>
        <option value="Atlanta Falcons">Atlanta Falcons</option>
        <option value="Baltimore Ravens">Baltimore Ravens</option>
        <option value="Buffalo Bills">Buffalo Bills</option>
        <option value="Carolina Panthers">Carolina Panthers</option>
        <option value="Chicago Bears">Chicago Bears</option>
        <option value="Cincinnati Bengals">Cincinnati Bengals</option>
        <option value="Cleveland Browns">Cleveland Browns</option>
        <option value="Dallas Cowboys">Dallas Cowboys</option>
        <option value="Denver Broncos">Denver Broncos</option>
        <option value="Detroit Lions">Detroit Lions</option>
        <option value="Green Bay Packers">Green Bay Packers</option>
        <option value="Houston Texans">Houston Texans</option>
        <option value="Indianapolis Colts">Indianapolis Colts</option>
        <option value="Jacksonville Jaguars">Jacksonville Jaguars</option>
        <option value="Kansas City Chiefs">Kansas City Chiefs</option>
        <option value="Las Vegas Raiders">Las Vegas Raiders</option>
        <option value="Los Angeles Chargers">Los Angeles Chargers</option>
        <option value="Los Angeles Rams">Los Angeles Rams</option>
        <option value="Miami Dolphins">Miami Dolphins</option>
        <option value="Minnesota Vikings">Minnesota Vikings</option>
        <option value="New England Patriots">New England Patriots</option>
        <option value="New Orleans Saints">New Orleans Saints</option>
        <option value="NY Giants">NY Giants</option>
        <option value="NY Jets">NY Jets</option>
        <option value="Philadelphia Eagles">Philadelphia Eagles</option>
        <option value="Pittsburgh Steelers">Pittsburgh Steelers</option>
        <option value="San Francisco 49ers">San Francisco 49ers</option>
        <option value="Seattle Seahawks">Seattle Seahawks</option>
        <option value="Tampa Bay Buccaneers">Tampa Bay Buccaneers</option>
        <option value="Tennessee Titans">Tennessee Titans</option>
        <option value="Washington Commanders">Washington Commanders</option>
    </select>
    <select id="positionFilter" class="form-control">
        <option value="">Select Position</option>
        <option value="QB">QB</option>
        <option value="RB">RB</option>
        <option value="WR">WR</option>
        <option value="TE">TE</option>
    </select>
    <select id="sourceFilter" class="form-control">
        <option value="">Select Source</option>
        <option value="Coach">Coach</option>
        <option value="Player">Player</option>
        <option value="Reporter">Reporter</option>
    </select>
</div>
<div class="filter-bar mt-2">
    <label for="startDate">Start Date:</label>
    <input type="date" id="startDate" class="form-control">
    <label for="endDate">End Date:</label>
    <input type="date" id="endDate" class="form-control">
    <select id="weekFilter" class="form-control">
        <option value="">Select Week</option>
        <option value="Pre Week 1">Preseason Week 1</option>
        <option value="Pre Week 2">Preseason Week 2</option>
        <option value="Pre Week 3">Preseason Week 3</option>
        <option value="Week 1">Week 1</option>
        <option value="Week 2">Week 2</option>
        <option value="Week 3">Week 3</option>
        <option value="Week 4">Week 4</option>
        <option value="Week 5">Week 5</option>
        <option value="Week 6">Week 6</option>
        <option value="Week 7">Week 7</option>
        <option value="Week 8">Week 8</option>
        <option value="Week 9">Week 9</option>
        <option value="Week 10">Week 10</option>
        <option value="Week 11">Week 11</option>
        <option value="Week 12">Week 12</option>
        <option value="Week 13">Week 13</option>
        <option value="Week 14">Week 14</option>
        <option value="Week 15">Week 15</option>
        <option value="Week 16">Week 16</option>
        <option value="Week 17">Week 17</option>
        <option value="Week 18">Week 18</option>
    </select>
    <button id="pastWeek" class="btn btn-primary">Past Week</button>
    <button id="pastMonth" class="btn btn-primary">Past Month</button>
    <button id="resetButton" class="btn btn-primary">Reset Filters</button>
</div>
<div id="quotes" class="mt-3"></div>
<div id="loadingSpinner" class="loading-spinner" style="display: none;">
    <div class="spinner-border text-primary" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<script
        type="text/javascript"
        src="{{ url_for('static', filename='dateFilters.js') }}"
></script>
<script type="text/javascript" src="{{ url_for('static', filename='quotes.js') }}"></script>
{% endblock %}

projectSteamIndex/website/templates/reports.html
{% extends "base.html" %} <!-- saying this template is the exact same as base.html and I can override any blocks that were defined within base.html -->
{% block title %}Reports{% endblock %} <!-- overriding the block within base.html -->
{% block stylesheet %}<link href="static/reports.css" rel="stylesheet"> {% endblock %} <!-- overriding the block stylesheet within base.html -->
{% block content %}

<h2>Generate Reports</h2>

<!-- Form for multiple reports -->
<form id="reportForm" method="POST" action="{{ url_for('auth.submit_reports') }}">
    <div id="reportSections">
        <!-- Initial report section -->
        <div class="report-section">
            <div class="form-group">
                <label for="playerName">Player Name</label>
                <input id="playerName" type="text" class="form-control" name="playerName[]" required autocomplete="off" list="playerNameSuggestions">
                <datalist id="playerNameSuggestions">
                    <!-- Suggestions will be dynamically added here -->
                </datalist>
            </div>
            <div class="form-group">
                <!-- Date Field -->
                <div class="row">
                    <div class="col-sm-6">
                        <label for="reportDate">Date</label>
                        <input id="reportDate" type="date" class="form-control" name="reportDate[]" required>
                    </div>
                    <!-- Source Field -->
                    <div class="col-sm-6">
                        <label for="source">Source</label>
                        <input id="source" type="text" class="form-control" name="source[]" required>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="reportText">Report Text</label>
                <textarea id="reportText"class="form-control" name="reportText[]" rows="3" required></textarea>
            </div>
            <div class="form-group">
                <label for="question">Question (optional)</label>
                <textarea id="question"class="form-control" name="question[]" rows="2"></textarea>
            </div>
            <button type="button" class="btn btn-danger delete-report-btn" id="deleteReportBtn">
                <span class="fas fa-trash-alt"></span>
            </button>
        </div>
    </div>

    <!-- Button to add new report sections -->
    <button type="button" class="btn btn-success mb-2" id="addReportBtn">
        <span class="fas fa-plus"></span>
    </button>
    <!-- Button to reset all fields -->
    <button type="button" class="btn btn-secondary mb-2" id="resetAllFieldsBtn">
        <span class="fas fa-sync-alt"></span>
    </button>
    <!-- Submit button -->
    <button type="submit" class="btn btn-primary">Submit All Reports</button>
</form>


<script
        type="text/javascript"
        src="{{ url_for('static', filename='reports.js') }}"
></script>
{% endblock %}

projectSteamIndex/website/templates/videos.html
{% extends "base.html" %} <!-- saying this template is the exact same as base.html and I can override any blocks that were defined within base.html -->
{% block title %}Videos{% endblock %} <!-- overriding the block within base.html -->
{% block stylesheet %}<link href="static/videos.css" rel="stylesheet"> {% endblock %} <!-- overriding the block stylesheet within base.html -->
{% block content %}
<h2>Video Manager</h2>
<button type="submit" class="btn btn-primary" onClick="download_yt()">Download</button>
<p id="result"></p>
<button id="deleteSelected" class="btn btn-danger" disabled>Delete Selected</button>
<div class="filter-container">
    <label for="teamFilter">Filter by Team:</label>
    <select id="teamFilter" class="form-control">
        <option value="all">Select Team</option>
    </select>
</div>
<table id="videosTable" class="table">
    <thead>
    <tr>
        <th></th>
        <th>Title</th>
        <th>Team</th>
        <th>Date Published</th>
        <th>Duration</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <!-- Video rows will be added here dynamically -->
    </tbody>
</table>
<script
        type="text/javascript"
        src="{{ url_for('static', filename='videos.js') }}"
></script>
{% endblock %}